from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(120), nullable=False)
    name = db.Column(db.String(80))
    age = db.Column(db.Integer)
    sex = db.Column(db.String(10))
    weight = db.Column(db.Float)
    height = db.Column(db.Float)
    goal = db.Column(db.String(20))
    is_vegan = db.Column(db.Boolean)
    daily_calories = db.Column(db.Integer)
    remaining_calories = db.Column(db.Integer)
    last_reset = db.Column(db.DateTime)

class Recipe(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    ingredients = db.Column(db.Text)
    energy_per_serving_kcal = db.Column(db.Float)
    protein_g = db.Column(db.Float)
    carbohydrate_g = db.Column(db.Float)
    fat_g = db.Column(db.Float)
    image = db.Column(db.String(255))
    serving_size = db.Column(db.Integer)
    prep_time_in_mins = db.Column(db.Integer)
    cook_time_in_mins = db.Column(db.Integer)
    is_vegetarian = db.Column(db.Boolean)
    is_breakfast = db.Column(db.Boolean)
    is_lunch = db.Column(db.Boolean)
    is_snack = db.Column(db.Boolean)
    is_dinner = db.Column(db.Boolean)
    fiber_g = db.Column(db.Float)
    instructions = db.Column(db.Text)
