"""Add is_vegetarian field to User model

Revision ID: 66bc39e3d067
Revises: 
Create Date: 2024-12-01 07:35:59.792614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66bc39e3d067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_log', schema=None) as batch_op:
        batch_op.drop_index('user_id')

    op.drop_table('nutrition_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vegetarian', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_vegetarian')

    op.create_table('nutrition_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('calories', mysql.FLOAT(), nullable=True),
    sa.Column('protein', mysql.FLOAT(), nullable=True),
    sa.Column('carbs', mysql.FLOAT(), nullable=True),
    sa.Column('fat', mysql.FLOAT(), nullable=True),
    sa.Column('fiber', mysql.FLOAT(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='nutrition_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('nutrition_log', schema=None) as batch_op:
        batch_op.create_index('user_id', ['user_id', 'date'], unique=True)

    # ### end Alembic commands ###
